# Generated by Django 5.2.5 on 2025-09-10 06:02

import banking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_number',
            field=models.CharField(default=banking.models.generate_account_number, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_type',
            field=models.CharField(default='Savings', max_length=50),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('fee', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccounts')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
